/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{gjs,gts,hbs,html,js,ts}'],
  theme: {
    extend: {},
  },
  plugins: [require('@tailwindcss/typography'), require('daisyui')],

  daisyui: {
    themes: [
      'light',
      'dark',
      'acid',
      'aqua',
      'autumn',
      'black',
      'bumblebee',
      'business',
      'cmyk',
      'coffee',
      'corporate',
      'cupcake',
      'cyberpunk',
      'dim',
      'dracula',
      'emerald',
      'fantasy',
      'forest',
      'garden',
      'halloween',
      'lemonade',
      'lofi',
      'luxury',
      'night',
      'nord',
      'pastel',
      'retro',
      'sunset',
      'synthwave',
      'valentine',
      'winter',
      'wireframe',
    ],
  },
};
